server:
  port: 8083

spring:
  application:
    name: order-service
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: 123456

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
