server:
  port: 8081

spring:
  application:
    name: products-service
#  cache:
#    ehcache:
#      classpath:ehcache.xml

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
