server:
  port: 8084

spring:
  application:
    name: delivery-service
  cloud:
    function:
      definition: OrderDelivery
    stream:
      function:
        bindings:
          OrderDelivery-in-0: delivery

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
