server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  # standalone mode
  client:
    # 实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    registerWithEureka: false
    # 此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server
  cloud:
    config:
      discovery:
        enabled: false