server:
  port: 8082

spring:
  application:
    name: carts-service
  session:
    store-type: jdbc
  h2:
    console:
      enabled: true
      path: /h2

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
