server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/api/products/**
        - id: carts-service
          uri: lb://carts-service
          predicates:
            - Path=/api/cart/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/delivery/**

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/